name: "Deploy Godot Project"

on:
  workflow_call:
    inputs:
      godot_version:
        required: true
        type: string

env:
  GODOT_VERSION: ${{ inputs.godot_version }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: barichello/godot-ci:${{ inputs.godot_version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Move HTML5 templates into position
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

    - name: Create staging directory
      run: mkdir -v -p ./build/web

    - name: Create .env file
      run: |
        touch .env
        echo API_URL=${{ vars.API_URL }} > .env
        cat .env

    - name: Build project
      run: godot -v --headless --export-release "Web" ./build/web/index.html

    - name: Add coi-service-worker
      run: |
        git clone https://github.com/gzuidhof/coi-serviceworker.git
        mv coi-serviceworker/coi-serviceworker.js build/web/coi-serviceworker.js
        sed -i '3 i <script src="coi-serviceworker.js"></script>' ./build/web/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
